### ISSUE TITLE
Incorrect co-travelers count on seat chart page

### ISSUE THREAD

**Issue by sylbakar** [US-CBP/GTAS-UI#633]
**Describe the bug**
On seat chart page, number of co-traveler seat icons does not match with Legend co-travelers' number
**To Reproduce**
1. Go to seat chart page for any passenger who has  co-travelers
2. Count the co-traveler icons on seat diagram
3. Compare with Legend co-traveler number
4. See number mismatch

**Expected behavior**
number of co-travelers seat icons should match with Legend co-travelers number
**Screenshots**
![co-travelersnumber](https://user-images.githubusercontent.com/49790901/106625568-c6a7cf80-6544-11eb-8538-1a01af9f87cf.jpg)

**Desktop (please complete the following information):**
tested in dev environment

**Comment by gtasautumn** [comment]
Some passengers are being duplicated in the data sent for this page. Found this on dev and locally on this branch. I have a flight with 200 passengers, but the seat data returned has 224 rows, and some are dupes. This is causing the co-traveler counts to be off for those duplicated passengers who have cotravelers since they show up in the cotraveler array twice as well. If there's not a separate ticket for that, we can fix it here.

![seatsCounts](https://user-images.githubusercontent.com/49160279/106951894-58a70800-66fe-11eb-9b10-b59c0a9a9d9e.JPG)
![seatsCounts2](https://user-images.githubusercontent.com/49160279/106951896-58a70800-66fe-11eb-84f3-84d67be0560f.JPG)

**Comment by sylbakar** [comment]
Tested in dev environment and found matched count for co- travelers.
