### ISSUE TITLE
Downloading file in Attachments page is not working

### ISSUE THREAD

**Issue by sylbakar** [US-CBP/GTAS-UI#643]
**Describe the bug**
Any existing file in Attachments page is not being downloaded.
**To Reproduce**
1. Go to any passenger detail page
2. Click on Attachments tab
3. Click on Action drop down for any existing file.
4. Select Download file.
5. See the blank page, nothing is downloaded.

**Expected behavior**
Selected file should be downloaded.

**Screenshots**
![downloadfile](https://user-images.githubusercontent.com/49790901/107392681-ee101680-6ac7-11eb-96e9-01443083e57c.jpg)

**Comment by gtasautumn** [comment]
Can you take a look at this Jon? This is happening on dev, not local.

The download service is fetching the file with a raw url (no headers), and it is being misrouted as an http request rather than a fetch. If you attempt to download a file, it redirects you to [baseurl]/attachment?attachmentId=:id, which renders empty html. Suspect we need to be sending the request with headers (router='api') so it works on dev.

**Comment by tjwdev** [comment]
I'd been taking a look at this earlier today: window.open offers absolutely zero ways to add custom headers to it in the request. It would be potentially possible to pass it via get parameters, but that's not going to give docker an easy way to glean that information. 

I have a working solution where-in which we use the blob rather than basically download it straight from the request URL in a stream. That way the fetch can have the custom headers we need passed through it, the downside is the blob will be held in memory basically until it's streamed into a file download. Ultimately it's a smaller change than the initial findings that window.open was immutable basically was leading me to believe.

**Comment by sylbakar** [comment]
Tested in dev environment and found downloading did not happen, got network error status 400.
![image](https://user-images.githubusercontent.com/49790901/110003286-3942d100-7ce4-11eb-8d5d-104f1d5448ed.png)

**Comment by gtasautumn** [comment]
This one failed test. Jon pls take a look.

**Comment by sylbakar** [comment]
Tested in dev and found file downloading worked. The test passed.
