### ISSUE TITLE
flightpax | DOB Column filtering with leading 0 does not work

### ISSUE THREAD

**Issue by sylbakar** [US-CBP/GTAS-UI#675]
**Describe the bug**
Entering any date with leading 0 for single digit month or day is not displaying any result

**To Reproduce**
1. Go to fligthpax
2. Click on DOB Column filter
3. Enter any existing date which has single digit month or day with leading 0
4. See no result.

**Expected behavior**
Desired existing date should be displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/49790901/109723076-9bcc8d80-7b7b-11eb-963e-f9324ed7dae7.png)

**Desktop (please complete the following information):**
 tested in dev

**Comment by gtasautumn** [comment]
So in this case, there's not a lot we can do if the user enters the date in a different format than is displayed in the grid other than capture the click events and reformat the text entered, which I don't think is ideal. 

The issue is that the table requires dates to be converted to a string so it can match the grid data to the string you enter in the filter. So if you enter "3/5", it doesn't know that it means March 5th and it doesn't know that any rows with "03/05" should match it. There's not much we can do to get around that.

**Comment by sylbakar** [comment]
Tested in dev and looked to me filtering with leading 0 worked.
